project:
  type: website

website:
  title: "Geospatial Analytics"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

