project:
  type: website

website:
  title: "Geospatial Analytics"
  navbar:
    background: success
    left:
      - text: Hands-on Exercises
        menu: 
          - href: Hands-on_Ex/Hands-on_Ex1(2).qmd
          - href: Hands-on_Ex/Hands-on_Ex1.qmd
          - href: Hands-on_Ex/Hands-on_Ex2.qmd
          - href: Hands-on_Ex/Hands-on_Ex3.qmd
          - href: Hands-on_Ex/Hands-on_Ex4.qmd
      - text: Take-home Exercises
        menu: 
          - href: TakeHomeEx/ex1.qmd
          - href: TakeHomeEx/ex2.qmd
      - text: In-class Exercises
        menu: 
          - href: InClass_Ex/InClass_Ex1.qmd
          - href: InClass_Ex/InClass_Ex2.qmd
          - href: InClass_Ex/InClass_Ex3.qmd
          - href: InClass_Ex/InClass_Ex4.qmd
         
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

