project:
  type: website

website:
  title: "Geospatial Analytics"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
          - href: Hands-on_Ex1/Hands-on_Ex1(2).qmd
          - text: Hands-on Exercise 1
          - href: Hands-on_Ex1/Hands-on_Ex1.qmd
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
         
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

